-- set up
require("chris.plugins-setup")
require("chris.core.options")
require("chris.core.keymaps")
require("chris.core.colorscheme")
-- plugins
require("chris.plugins.comment")
require("chris.plugins.nvim-tree")
require("chris.plugins.lualine")
require("chris.plugins.telescope")
require("chris.plugins.nvim-cmp")
require("chris.plugins.autopairs")
require("chris.plugins.treesitter")
require("chris.plugins.gitsigns")
require("chris.plugins.md")
-- lsp
require("chris.plugins.lsp.mason")
require("chris.plugins.lsp.lspconfig")
require("chris.plugins.lsp.flutter-tools")
require("chris.plugins.lsp.lspsaga")
require("chris.plugins.lsp.null-ls")
